apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube
  namespace: default
spec:
  dnsNames:
    - codeops.cf
    - sonarqube.codeops.cf
  secretName: sonarqube-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
